let arr = [12, 23, 11, 23, 13, 4324];
let arr2 = [40, 50, 60, 70, 23, 43, 23];
let con = arr.toString();
console.log(typeof arr);
console.log(typeof con);
let joinArr = arr.join("-");
console.log(joinArr);
console.log(typeof joinArr);
let poP = arr.pop();
console.log(arr);
let pusH = arr.push(201);
console.log(arr);
let shFt = arr.shift(12);
console.log(shFt, arr);
let conCat = arr.concat(arr2);
console.log(conCat);
